version: '3'
services:
  backend:
    image: webbylabhub/movies
    environment:
      - API_URL=${API_URL} # Зверніть увагу, що тут не вказано конкретне значення, використовується ${API_URL}

  your-app:
    image: indian0ch/movies
    environment:
      - API_URL=${API_URL} # Тут також залишаємо змінну оточення
    ports:
      - "3000:3000"
    depends_on:
      - backend
