version: '3'
services:
  backend:
    image: webbylabhub/movies
    environment:
      - API_URL=${API_URL}
    ports:
      - "80:80"

  testweblab:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_URL=${API_URL}
    ports:
      - "3000:3000"

