version: '3'
services:
  movies:
    image: webbylabhub/movies
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=movies
    depends_on:
      - database
  database:
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=movies
